apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: userprofile-blue-green
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sivamohanreddy202/Shine-GitOps-Project.git
    targetRevision: main
    path: Retail-chart
    helm:
      values: |
        userprofile:
          activeVersion: blue
  destination:
    server: https://98765208BC2203CD9EC9F3BCD6F1E926.gr7.us-west-1.eks.amazonaws.com
    namespace: retail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
